name: check_python_version

on:
  push:
    branches:
      - check_python_version
        
jobs:
  check_python_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install_python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: pip_update
        run: python -m pip install --upgrade pip
        
      - name: print_python_version
        run: python --version
