name: main

on:
  push:
    branches:
      - main

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip_update
        run: python -m pip install --upgrade pip

      - name: install_flake8
        run: python -m pip install flake8

      - name: print_python_version
        run: python --version

      - name: run_flake8
        run: flake8 .

      - name: run_unit_tests
        run: python -m unittest test.py
